name: 'Release'
description: 'Runs Semantic Release'
inputs:
  dry_run:
    description: 'Whether to perform a dry run'
    required: false
    default: false
  node_version:
    description: 'Node version'
    required: false
    default: '16'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Semantic Release Dry Run
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17
        branches: main
        dry_run: ${{ inputs.dry_run }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
