name: dry-run

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci
      - uses: ./.github/actions/release
        with:
          dry_run: true